version: 2

sources:
  - name: raw_api_dump
    database: dw-healthcare-dbt
    schema: raw_api_dump
    tables:
      - name: healthcare_staff
      - name: hospital_beds
      - name: population_state

models:
  - name: stg_healthcare_staff
    description: "Staging model for healthcare staff"
    columns:
      - name: date
        description: "Date of record"
        tests:
          - not_null
      - name: type
        description: "Type of staff"
      - name: staff
        description: "Number of staff"
        tests:
          - not_null
      - name: state
        description: "State name"

  - name: stg_hospital_beds
    description: "Staging model for hospital beds"
    columns:
      - name: beds
        description: "Number of hospital beds"
        tests:
          - not_null
      - name: date
        description: "Date of record"
      - name: type
        description: "Type of bed"
      - name: state
        description: "State name"

  - name: stg_population_state
    description: "Staging model for population by state"
    columns:
      - name: year
        description: "Year of record"
        tests:
          - not_null
      - name: state
        description: "State name"
        tests:
          - not_null
      - name: sex
        description: "Gender"
      - name: age
        description: "Age group"
      - name: ethnicity
        description: "Ethnicity group"
      - name: population
        description: "Population count"
        tests:
          - not_null