name: 'dw_healthcare'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dw_healthcare'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dw_healthcare:   
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts